jwt:
  secret: 'PryalkinPavelPavlovich'

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recreation_center
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate:
      ddl-auto: true
